- name: create an EC2 instance
  hosts: local
  connection: local
  vras: 
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-045897fa6d8ffd258"
    zone_id: "Z07503961RHS7OI25U00O"
    domain_name: "devtraining.icu"
    instance: 
    - mongodb
  tasks:
  - name: create an EC2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      secuirty_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
  loop: "{{ instance }}"
