- name: configure mysql on server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql on server
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: mysql service 
    ansible.builtin.service:
      state: started
      enabled: yes
  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1